### ISSUE TITLE
h5ai question: how do you copy a link to a file?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/datastore#5]
I am frequently perplexed by my inability to figure out how to copy a URL for a file out of the
interface to https://legumeinfo.org/data. right click on the folder hierarchy gives me the copy link address option as expected (in Chrome), but right click on files in the main part of the UI does not. 
It's not clear to me by looking at the page source exactly how this works, but seems that there is a heavy layer of javascript between me and the resources. Can't even copy the text of the file names to paste them elsewhere. It annoys me, but maybe I'm the only one. Figured it can't hurt to ask..

**Comment by vivekkrish** [comment]
Hi @adf-ncgr, I came across this issue as I was trolling through GitHub to take a look at the Zenhub issue moving functionality that you spoke about.

Last week, when I was using the https://legumefederation.org/data/public interface (which I'm assuming is the exact same as https://legumeinfo.org/data/public), I noticed that in order to get a link to a particular file, the **right-click** needs to happen when the mouse is hovering over the text corresponding to the "File Name", "Last Modified" or "Size" values. Right-clicking in the empty space between the columns does nothing.

Hope this helps!

**Comment by adf-ncgr** [comment]
Thanks @vivekkrish ! I was just puzzling over why it seems different for me than what you describe; but then realized that on my mac laptop, it isn't right-click I'm using, it's ctrl-click (single button mouse). Maybe I've gotten confused about the appropriate gestures to use in mac-land; the ctrl-click works fine for regular links but I guess it's another layer of event handling when the js ui is involved. probably now that I know it does work as expected when you have a way to right-click a little googling will teach me what the magic salute is. I still struggle to understand which symbol means "ctrl" when mac keyboard shortcuts are being given...

**Comment by vivekkrish** [comment]
You're welcome, @adf-ncgr! It is definitely confusing.

I normally use the "Two Finger" tap gesture on my trackpad to trigger **right-click**, which seems to produce the expected behavior.

Ctrl+MouseClick (which also triggers **right-click**) seems to not work with the h5ai UI (it triggers the right-click context menu, but without the function that allows copying the link address).

And as for the various hieroglyphic symbols pertaining to Ctrl, Alt, Options, Shift, Command - I can never figure out which is which!

**Comment by adf-ncgr** [comment]
well, glad to hear at least I wasn't being completely an idiot. Oddly, the right-click seems to work in firefox, so I guess it is an obscure combination of factors. Maybe I can train myself to use the two-finger style, but I guess I can consider submitting an issue to h5ai maintainer since it's not just me who is seeing the Mac-Chrome-right-click issue.
