### ISSUE TITLE
Overall description of organism and "strain"

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/datastore#6]
Since I'm working on pure-datastore-loaded mines, one thing that's missing that's kind of important is a description of the organism and reference "strain" (call it what you will). It seems we should have a basic file describing, say, Phaseolus vulgaris in the top folder, and then under the strain-specific annotation folders have something about the particular line, e.g. G19833.

Here are examples of what BeanMine shows from data I curated from the lit, showing the sorts of info we should have in the DS.

![Screenshot_2019-05-08 BeanMine Report page](https://user-images.githubusercontent.com/5657219/57415528-ccc71b80-71b9-11e9-955e-f994692b103a.png)

![Screenshot_2019-05-08 BeanMine Report page(1)](https://user-images.githubusercontent.com/5657219/57415527-ccc71b80-71b9-11e9-9153-cd510aff6a07.png)

**Comment by adf-ncgr** [comment]
seems reasonable to me, although there's a potential for inconsistency with respect to strain-specific descriptors since we don't have "a folder" for a strain, due to the two-levels-flat rule of the current datastore structure; I suppose if we wanted to we could create a dataless strain folder just for this metainfo. Also, I'll note that level one isn't always a species (aka organism) since we have folders like "Gene_families" and "Arachis_sp". Presumably your code could be tolerant (ie ignore) when absent or can deal with higher level taxonomic designations where appropriate and present.

This might be a good place to put metainfo in addition to what you've capture thus far in the mines too. e.g. estimated genome sizes or chromosome counts (for the enthusiasts but also perhaps fun to display in a DSCensor context).

**Comment by sammyjava** [comment]
Well, to keep things simple, I'd like to just start with what I suggested so I can get those data into the DS-populated mines. One can embellish as we go along.

**Comment by cann0010** [comment]
I can imagine a new descriptive file at the outer folder level (Phaseolus_vulgaris, Gene_families, etc.), but I am reluctant to add a new metadata item within the terminal collections (e.g. G19833.gnm2.fC0g). The problem with putting it within the collections is that many of these relate to a common reference strain, and we wouldn't want to repeat the information about the strain in all of those collections. As an alternative, how about something like a "genotypes.yml" file in the outer folders. The first block would describe the species (or other contents of the directory), and subsequent blocks would describe the genotypes present in the directory.

**Comment by sammyjava** [comment]
Yeah that's fine, makes sense. I'd just like to have it somewhere. A single file that describes the plant material in this organism folder would be fine. In fact, for Cowpea, for example, we have lots of plant lines that are not assembled but I'd like to read those strain descriptions from a file in the DS. RIght now I have a Joe Carlson-type SQL updater that does that, which isn't ideal.

**Comment by cann0010** [comment]
As I start working on this, a few questions arise:
- How do you want to recognize a "genotype"? Should it be the genotype name component that's used in the directories - e.g. G198333, Wm82, A17_HM341?
- How to flag which genotypes should be "noticed" in a Mine? Presumably, not all Medicago genotypes will be picked up by the mine (or will they?) Note that the "application_status.txt" file (or whatever we call it) could be used to flag for a mine that a given collection should be processed.
- If we use yaml, what data structure should we use? We could use a list (~array) to enumerate the collection of genotypes ... but then how to store the descriptions relative to the genotype labels? I suppose it could be like the following - with the convention that the first word IS the genotype label. But this seems like a hacky convention to get what is effectively an array of hashes, i.e. [Wm82 => description, Lee => description] 

genotype: 
  - Wm82 The genotype "Williams 82" is a northern U.S. variety that has been widely used in soybean breeding projects. It is has resistance to XYZ and ASDF diseases.
 - Lee The genotype "Lee" is a southern U.S. variety whose name has three letters.

**Comment by sammyjava** [comment]
1. The actual plant line, so, yes, "Williams 82" or "G19833."
2. I'm not planning to be that fancy to "notice" things. I'll specify the genotypes to load. The issue of "current" was a convenience to auto-update the mines without specifying the new versions, but even that is a convenience.
3. I can create a format locally and we can go from there. I figured on something pretty much as you've suggested. I normally use tab-delimited files, so something like
```
organism.taxonId   3847
organism.genus     Glycine
organism.species   max
organism.name      Glycine max
organism.commonName   soybean
organism.description Soybean is the predominant oil-seed legume; it produces a high-protein meal and has many industrial uses.
strain1.identifier  Wm82
strain1.name       Williams 82
strain1.origin      Northern United States
strain1.description Williams 82, the soybean cultivar used to produce the reference genome sequence, was derived from backcrossing a phytophthora root rot resistance locus from the donor parent Kingwa into the recurrent parent Williams.
strain2.identifier ...
...
```

**Comment by cann0010** [comment]
I've tried a few different formats. What I am liking best so far is prototyped in three places:
https://legumeinfo.org/data/public/Phaseolus_vulgaris/about_this_collection/
https://legumeinfo.org/data/public/Glycine_soja/about_this_collection/
https://legumeinfo.org/data/public/Glycine_max/about_this_collection/

I put the species-level fields and the strain-level fields into separate files because there is a one-to-many relationship, with the organism (Glycine max) pointing to several strains. In the strain "table", the strain.identifier serves, essentially, as the key for that record.

Why I used .yml: partly to keep _h5ai from rendering the .txt file! (The javascript-rendered .txt isn't selectable, and long lines don't wrap.)

Why I put the files into a directory (about_this_collection/): partly to keep things tidy, and partly to get it to float to the top of the directory listing. Weirdly, _h5ai doesn't seem to follow typical ASCII sort order (which would put "about" after "Wm82")

Let me know if there are things that you'd like changed.

**Comment by adf-ncgr** [comment]
I would like the description of phavu.G19833 changed so that it isn't about Glycine soja :)
otherwise, this seems fine to me so far, although I do have some mild philosophical reservations about allowing _h5ai behaviors determine our data representation; that said, I don't mind the data representation that resulted in this case, so will return to regularly scheduled navel-gazing...

thanks!

**Comment by adf-ncgr** [comment]
one other minor thing; it seems to me that the organism.name is likely completely redundant with the provided genus and species info. If there's a good reason to keep it, that's fine, just thinking it's one more place for us to get things slightly wrong. We might, however, want to consider adding the gensp code somewhere in the organism info, as the canonical place for us to declare, "it's glyma to us, not soybn, no matter what you may say uniprot!"...

**Comment by cann0010** [comment]
@adf-ncgr - I'm easy. 
@sammyjava - I think the data in in these files is mostly determined by the need of the mines.

**Comment by sammyjava** [comment]
I'm happy with these files. BTW I need the phavu -> 3885 map in a lot of places, so I've hardcoded those. But it's probably useful to have the LIS gensp in there since we use that instead of the NCBI  taxon ID.

**Comment by sammyjava** [comment]
Closing this, what you've implemented works fine.
